return {
        'lewis6991/gitsigns.nvim',
        { 'akinsho/toggleterm.nvim', version = 'v1.*' },
        'dstein64/vim-startuptime',
        'ellisonleao/dotenv.nvim',
        'f-person/git-blame.nvim',
        { 'folke/trouble.nvim',      dependencies = 'kyazdani42/nvim-web-devicons' },
        'goolord/alpha-nvim',
        'hiphish/rainbow-delimiters.nvim',
        'folke/lazydev.nvim',
        'hrsh7th/cmp-buffer',
        'hrsh7th/cmp-nvim-lsp',
        'hrsh7th/cmp-path',
        'hrsh7th/nvim-cmp',
        'kyazdani42/nvim-tree.lua',
        'kyazdani42/nvim-web-devicons',
        'L3MON4D3/LuaSnip',
        'mason-org/mason-lspconfig.nvim',
        'mason-org/mason.nvim',
        'mfussenegger/nvim-dap',
        'NeogitOrg/neogit',
        { 'neovim/nvim-lspconfig' },
        'numToStr/comment.nvim',
        'nvim-lua/plenary.nvim',
        'nvim-lualine/lualine.nvim',
        'nvim-telescope/telescope-frecency.nvim',
        { 'nvim-telescope/telescope-fzf-native.nvim', build = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' },
        { 'nvim-telescope/telescope.nvim',            dependencies = { 'nvim-lua/plenary.nvim' } },
        { 'nvim-treesitter/nvim-treesitter',          build = ':TSUpdate' },
        'nvimtools/none-ls.nvim',
        'rafamadriz/friendly-snippets',
        { 'rcarriga/nvim-dap-ui',   dependencies = { 'mfussenegger/nvim-dap' } },
        'RRethy/nvim-treesitter-endwise',
        'saadparwaiz1/cmp_luasnip',
        'theHamsta/nvim-dap-virtual-text',
        'tpope/vim-fugitive',
        'tpope/vim-repeat',
        'tpope/vim-surround',
        'windwp/nvim-autopairs',
        'stevearc/conform.nvim',
        { "catppuccin/nvim", name = "catppuccin", priority = 1000 }
    }

